service: svg-to-png-serverless

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1536
  timeout: 180

functions:
  convertToPng:
    handler: index.handler
    environment:
      DEBUG: '0'
    events:
      - http:
          path: /convert-to-png
          method: post
          cors: true

package:
  artifact: ./package.zip
  
plugins:
  - serverless-hooks-plugin
  - serverless-offline

custom:
  hooks:
    package:initialize:
      - npm run package